# FROM node:slim AS builder

# COPY package.json package-lock.json ./
# RUN npm ci
# RUN npm run build

# COPY . .

# #CMD ["sh", "-c", "npm run db:deploy && npm run dev"]

# CMD ["node", "dist/servers/express.js"]




FROM node:latest AS builder

RUN mkdir app

WORKDIR /app

COPY . .

RUN npm ci
RUN npx prisma generate
RUN npm run build


FROM node:latest AS runner

ENV NODE_ENV=production

WORKDIR /app
COPY --chown=node:node --from=builder /app/package.json .
COPY --chown=node:node --from=builder /app/dist .

RUN npm install --production
RUN npm cache clean --force

COPY --chown=node:node --from=builder  /app/generated ./generated

EXPOSE 3000

CMD ["sh", "-c", "npm run db:migrate:deploy && node servers/express.js"]