# fly.toml app configuration file generated for tcschoenbusch-api on 2025-08-09T15:57:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tcschoenbusch-api'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
